# composer require jwt-auth
# mkdir config/jwt
# openssl genrsa -out config/jwt/private.pem -aes256 4096
# winpty openssl genrsa -out config/jwt/private.pem -aes256 4096 (windows)
# openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
# winpty openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem (windows)

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
